### ISSUE TITLE
can not use Next.js getInitialProps() with react-waterfall connect().

### ISSUE THREAD

**Issue by mehrad77** [didierfranc/react-waterfall#100]
When I use `export default connect(state => state)(Component);`, The `getInitialProps()` of Next.js stops working. 

I made a [demo on CodeSandBox ](https://codesandbox.io/embed/helloworld-jrmig)here so you can see. 
is this `react-waterfall` problem or should figure it out with Next.js?

**Comment by mehrad77** [comment]
Hey @didierfranc, Sorry for rushing on you but can you give me a hint so I can start to work on a pull request to solve this?

**Comment by didierfranc** [comment]
Hi, never used react-waterfall with ssr, there are some issues about that subject you can check herehttps://github.com/didierfranc/react-waterfall/issues?q=is%3Aissue+ssr+is%3Aclosed
