### ISSUE TITLE
Redux-devtools-extension integration

### ISSUE THREAD

**Issue by elisherer** [didierfranc/react-waterfall#17]
Hi,

I forked `react-waterfall-example` and started implementing an integration with `redux-devtools-extension`.
It works very well for viewing, I havn't got the yet to go over the time travel, so I combined your devTool with mine.

Have a see:
https://github.com/elisherer/react-waterfall-example/blob/feature/redux-devtools-extension/src/reduxDevTool.js

![image](https://user-images.githubusercontent.com/1045347/38084546-fc961454-3355-11e8-87aa-c2087f404427.png)

**Comment by elisherer** [comment]
UPDATE:
I got time travel working...

![waterfall-redux-devtool](https://user-images.githubusercontent.com/1045347/38110287-c0ac05b8-33a3-11e8-8369-5e88dfafcf2f.gif)

Also got the dispatcher working as well, even passing arguments:
For example: "this.increment", "increment" & "increment(23)" will all work (and the last will actually pass the argument)

A thing that I think we should have is logging the action's arguments and those are not shared with the middleware (PR maybe?)

**Comment by didierfranc** [comment]
Yes it could be great to have it !

**Comment by didierfranc** [comment]
I think we can close this ;)
