### ISSUE TITLE
I/O and other possible side effects

### ISSUE THREAD

**Issue by brodybits** [didierfranc/react-waterfall#24]
Desired but not covered by the existing documentation (#5 [[1]](https://github.com/didierfranc/react-waterfall/issues/5)).

Asynchronous (Promise-based) actions are supported but not documented ([src/index.js#L34-L36 (2)](https://github.com/didierfranc/react-waterfall/blob/master/src/index.js#L34-L36), <https://github.com/didierfranc/react-waterfall/issues/5#issuecomment-378620109> ([[3]](https://github.com/didierfranc/react-waterfall/issues/5#issuecomment-378620109))), already covered by the proposed tests contributed in #22 ([[4]](https://github.com/didierfranc/react-waterfall/pull/22)).

It *should* be possible for a developer to perform both synchronous and asynchronous side effects including I/O within react-waterfall actions but this is not documented. I am also not 100% convinced that this is the best way and would be happy to discuss some alternative ideas.

[1] #5
[2] <https://github.com/didierfranc/react-waterfall/blob/master/src/index.js#L34-L36>
[3] <https://github.com/didierfranc/react-waterfall/issues/5#issuecomment-378620109>
[4] #22

**Comment by didierfranc** [comment]
Don't hesitate to propose update of documentation and new examples, there are big lacks.
