### ISSUE TITLE
Consumer: make mapStateToProps optional?

### ISSUE THREAD

**Issue by joelmukuthu** [didierfranc/react-waterfall#25]
If I only want to use `actions` with a `Consumer`, as opposed to straight up importing actions from my store, I'm forced to add a noop `mapStateToProps`. Am I using the consumer in a wrong fashion or is this a viable use case? If yes I can submit a PR for that :)

**Comment by elisherer** [comment]
The `actions` object is created when doing `initStore`, you can import it on every module without `connect`ing.

**Comment by joelmukuthu** [comment]
Okay. So is using `Consumer` only to get `actions` not considered good practice?

**Comment by elisherer** [comment]
No. Contrary to redux, react-waterfall exposes its bound actions right from the store initialization.
Using redux, you can do that too, (i.e. after creating the store, run `bindActionCreators(actionCreatorsObject, store.dispatch)`
