### ISSUE TITLE
Manage state on loading

### ISSUE THREAD

**Issue by stefensuhat** [didierfranc/react-waterfall#27]
Hi, Thanks for this great package! So much simple. But I have this question:

At redux you can easily define type for example:

`FETCH_USERS_LOADING` and the payload can only return `{loading: true}` to show loading at front section

How do you handle this on waterfall?

**Comment by stefensuhat** [comment]
i just see https://github.com/didierfranc/react-waterfall/pull/6 

one of the solution i think.

**Comment by elisherer** [comment]
Same.
You create two actions:
```js
  actions: {
    setLoading: () => ({ loading: true })
    fetchUsers: () => fetch('http://example.com/users')
         .then(response => response.json())
         .then(users => ({ users, loading: false })) // transfer json response to the setState arguments
         .catch(error => ({ error, loading: false })) // in case of error, save it and stop loading
  }
```

then use by:
```js
  setLoading();
  fetchUsers();
```

Changing the way actions are written would be to over complicate it.

(*)
If you really want to make it one action to do both, 
you will have to write a middleware that does it once the `setLoading` action was dispatched, 
something along the line of `callApi(url)` which at first sets the `url` in a state of pending, 
and the middleware will fetch the data and automatically set the pending state to finished once done.

**Comment by ladislavP** [comment]
Hello. Thanks for awesome package.. 
Maybe a dummy question but wan't it good if the "dispatch of action" would be async, so it will return a promise. So I can simply do:
`
await actions.actionOne();
await actions.actionTwo();
`

**Comment by elsangedy** [comment]
```javascript
import axios from 'axios'
import { initStore } from 'react-waterfall'
import devtools from 'react-waterfall-redux-devtools-middleware'

const store = {
  initialState: {
    loading: false,
    items: [],
  },
  actions: {
    all: async () => {
      try {
        const { data } = await axios.get('http://my-url.com/api/endpoint')

        return {
          loading: false,
          items: data,
        }
      } catch (err) {
        return {
          loading: false,
        }
      }
    },
    fetch: (state) => {
      actions.all()

      return {
        loading: true,
      }
    }
  },
}

export const { Provider, connect, actions } = initStore(store, !process.env.NODE_ENV !=== 'production' && devtools())
````

**Comment by didierfranc** [comment]
Great answer I close the issue

**Comment by elsangedy** [comment]
```javascript
...
all: async (param, other) => ...
...
```

```javascript
...
actions.app('first_param', 'other param')
...
```

**Comment by rkrayovskyy** [comment]
obviously, but return {...} is not setting state then... probably issue is elsewhere, will keep looking. thanks anyway!
