### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by kumarabhishek** [didierfranc/react-waterfall#31]
Can we host a better documentation and demo for quick and better understanding of feature. Let me know if you need my help.

**Comment by didierfranc** [comment]
Yes it could be great

**Comment by RyanNerd** [comment]
I'm new to React. I finally have my head wrapped around the Context API. `react-waterfall` seems to borrow heavily from Redux requiring that I have a master's degree in Redux before I can even attempt to try to use `react-waterfall`. Documentation is sparse right now, but I like what I've read so far -- but without better docs practical implementation is beyond my understanding.

**Comment by didierfranc** [comment]
Don't hesitate to open an issue exposing what you want to achieve and you'll probably find help ;)
