### ISSUE TITLE
Props changes doesnt reflect to children component when used with connect

### ISSUE THREAD

**Issue by lanzosuarez** [didierfranc/react-waterfall#52]
Props is not sync with the connect and the component.

 When i toggle a state change props changes inside the connect
 
![image](https://user-images.githubusercontent.com/18522203/40038021-ad1e12f2-5842-11e8-86ee-0991557fcf71.png)
But the changes doesnt reflect to the passed component
![image](https://user-images.githubusercontent.com/18522203/40037871-02e468ae-5842-11e8-8030-b796e63b2279.png)

See. editVisible is true inside the connect but false in the child component

**Comment by elisherer** [comment]
Fixed on #49, breaking change, will be up on next version.

**Comment by nlucero** [comment]
Any ETA on the next version?

**Comment by didierfranc** [comment]
I'll publish it soon I need to take time to rewrite flowtypes before publishing the 4.0.0

**Comment by didierfranc** [comment]
Is this test covering this issue ? https://github.com/didierfranc/react-waterfall/blob/master/src/__test__/index.test.js#L30-L40
