### ISSUE TITLE
v4 is coming

### ISSUE THREAD

**Issue by didierfranc** [didierfranc/react-waterfall#54]
## `@Contributors`
@elisherer @hansoksendahl @vanthiyathevan @klassicd @FlorianRappl @jgbright @mottox2 @emilioicai @callumlocke @chrismcleod

I've started to rewrite `react-waterfall` from scratch here https://github.com/didierfranc/react-waterfall/tree/master, in order to make the code cleaner, splited and with a better flow type coverage to facilitate contributions and comprehension.

## Some questions

1. Is `<Consumer />` really useful ? I'm not using it in my projects, I prefer `connect`, should we keep it ?
2. We used to access actions from two way: `store.actions` or directly from the consumer/connect props/arguments. In the current `v4` draft you can only connect the state, and actions are available through `store.actions` only.

I believe if we make API even simpler, with only one way to do something it could be better.

**Comment by elisherer** [comment]
1- drop Component.
2- seems right.

**Comment by FlorianRappl** [comment]
Hi @didierfranc - thanks for initiating the discussion.

1. Fully agree, we do the same.
2. We have some use-case for also exporting actions even though it could be also solved within a component. Overall, I feel that having the ability to export `actions` gives more flexibility (hence I guess the initial design). Either way works. Personally, I would leave this part as it is.

Thanks for this wonderful abstraction!

**Comment by domialex** [comment]
I love the fact that you can export `actions`; it also allows us to call `actions` within `actions`.

**Comment by didierfranc** [comment]
I tried to connect a little part of redux devtools to react-waterfall only during dev https://github.com/didierfranc/react-waterfall/commit/7a8455bff69149bad4174faeb135fdcbd80b4b1c#diff-dd92fe9d8fb8e8088bb0eaae3244cce2

**Comment by vanthiyathevan** [comment]
One feature that would be nice is to pass part of initial state to `Provider` as prop.

**Comment by didierfranc** [comment]
Current WIP on master seems good for me, I'm waiting for more feedback before releasing it. Thanks all !

**Comment by domialex** [comment]
Don't know if it's possible, but could there be a way to get a promise when calling an `async` action?

**Comment by didierfranc** [comment]
I think it will be easy to implement it do you have usecase example ?

**Comment by domialex** [comment]
For example waiting for an action to finish before changing views with a navigator? Is this a good use case?

**Comment by klassicd** [comment]
I run into a similar use case a lot. 

To insure an action completed successfully, you have to `connect` the store variable that was  modified and use `getDerivedStateFromProps` to watch for changes and then take action (e.g. Redirect).  This is strange as many of my actions simply update a catch all `message` in the store which displays a snackbar confirmation.  I have to overcomplicate the store design by tracking individual entities that have been updated to properly redirect/close components.

Being able to await an action is interesting way to tackle this, although I'm not sure what the promise would return as it's value?  Would it return the modified state or just resolve/reject undefined?

**Comment by domialex** [comment]
Using `getDerivedStateFromProps` is definitely a good idea, but forces us to connect everything that must use `actions`.
I would vote to simply resolve.

**Comment by slorber** [comment]
Hey @didierfranc , just wanted to mention that new developments should rather not be done on master directly, this is confusing for newcomers like me, as it looks like I have to use the v3 branch to be able to consult the doc/code/examples I need to.

**Comment by slorber** [comment]
sure, will try it

**Comment by didierfranc** [comment]
I published a new beta don't hesitate to try it ;)

**Comment by kirsantov** [comment]
Where I can view migration notes? After upgrade to 4 version and change initStore to createStore I have not understandable eror: Uncaught TypeError: Invalid attempt to spread non-iterable instance

**Comment by didierfranc** [comment]
https://github.com/didierfranc/react-waterfall#basics your config store shape is probably wrong

**Comment by uxzc** [comment]
@kirsantov It seems that now you need to list your middleware in an array in createStore. Otherwise it throws the same error for me
`createStore( store, [myCustomMiddleware] )`

**Comment by kirsantov** [comment]
store/
- index.js
`import createStore from 'react-waterfall';
import reduxDevTools from 'react-waterfall-redux-devtools-middleware';
import RealAPI from '../api/RealAPI';
import config from '../config';

import initialState from './state';
import actionsCreators from './actions';

export const api = new RealAPI(config.apiUrl);

const store = {
  initialState,
  actionsCreators,
};

export const {
  Provider, connect, actions,
} = (config.DEV) ?
  createStore(store, reduxDevTools()) :
  createStore(store);`

state.js:
`
export default {
  userTimeZone: '',
  mobileScreen: 1,
  showTransactionDetail: null,
  order: {
    id: null,
    redirect: null,
  },
 ...
};
`
actions.js:
`
export default {
  increment: ({ count }) => ({ count: count + 1 }),
  setLang: ({ lang }, language) => ({
    lang: language,
  }),
...
};
`

index.jsx
`
...
import { Provider, connect, actions, api } from './store';
...
let Application = ({ lang }) => {
  let locale;
  switch (lang) {
    case 'ru':
    case 'ua':
      locale = 'ru';
      break;
    default:
      locale = 'en';
  }
  return (
    <IntlProvider
      locale={locale}
      messages={messages[lang]}
    >
      <App />
    </IntlProvider>
  );
};

Application = connect(state => ({ lang: state.lang }))(Application);
ReactDOM.render(
  <Provider>
    <Application />
  </Provider>,
  document.getElementById('root'),
);
`


Where I did mistake?

**Comment by kirsantov** [comment]
@uxzc it works

**Comment by didierfranc** [comment]
BTW you don't need redux devtools anymore it's included by default https://github.com/didierfranc/react-waterfall#devtools

**Comment by kirsantov** [comment]
Another yet error:
```
let Inputer = (props) => {
  console.log(props);
  const { intl, purchaseForm } = props;
  const { changePurchaseForm, checkWalletAddr } = props.actions;
  return (
...
    <input
          value={purchaseForm.walletAddress}
          onChange={({ target: { value } }) => changePurchaseForm('walletAddress', value)}
          onBlur={() => checkWalletAddr()}
          onKeyUp={() => checkWalletAddr()}
          onPaste={({ clipboardData }) => checkWalletAddr(clipboardData)}
        />
...
  );
};

Inputer = compose(
  injectIntl,
  connect(state => ({
    lang: state.lang,
    purchaseForm: state.purchaseForm,
  })),
)(Inputer);
```
Uncaught TypeError: Cannot destructure property `changePurchaseForm` of 'undefined'

and in console.log(props) no actions in props

**Comment by didierfranc** [comment]
Open new issues if you encounter any problem, fyi actions have been removed from props
