### ISSUE TITLE
Improving multiple actions calls

### ISSUE THREAD

**Issue by nlucero** [didierfranc/react-waterfall#55]
There seems to be a bug when calling two actions consecutively. The second action (even if they both are synchronous) receives an outdated version of the state (as if the first action never executed).

Bug reproduced [here](https://codesandbox.io/s/l4jn041m8z): When you press the button two actions are executed: `add` and `double`. `double` receives the state prior to the execution of `add`.

Works correctly if you either `await` the first call or you defer the second action call forward in the event loop (e.g. `setImmediate`).

**Comment by elisherer** [comment]
maybe use setState with a function instead of an object.

**Comment by didierfranc** [comment]
We must add this to the README or to the non existing react-waterfall doc 😕

**Comment by didierfranc** [comment]
This seems to be the same problem https://github.com/didierfranc/react-waterfall/issues/54#issuecomment-391930751

**Comment by elisherer** [comment]
If there is a native way to make the lib more correct, I think it's preferable. forcing to use tranpilation for async-await is not good.

**Comment by didierfranc** [comment]
What about returning Promise for all actions even if there is no async inside ?

The following will work and we could wait for action to finish
```jsx
<button
  onClick={async () => {
    await actions.add();
    actions.double();
  }}
>
  +
</button>
```

**Comment by nlucero** [comment]
@elisherer You are not forced to use `async-await`, you could always `.then` the returned `Promise`.

@didierfranc I think we have two solutions here: One would be, as you said, return a `Promise` from every action (even sync ones) which would get resolved on the internal `setState` callback.
The other one is the one that @elisherer mentioned: Use functional `setState` which always guarantees that you receive the updated state.

And yes, `await`ing the action result right now is a dirty trick that abuses JS event loop 😅

**Comment by didierfranc** [comment]
Functional setState doesn't seem to be working for that particular case, so I dit that https://github.com/didierfranc/react-waterfall/commit/1db2cddf1256ccec1c8d9b8f63091f24e9f22d80#diff-1fdf421c05c1140f6d71444ea2b27638

**Comment by elisherer** [comment]
@didierfranc, Sorry to open this again, but I do think that functional setState should work and enable you to run consecutive actions without await.
Doing consecutive actions after promise resolve will cause an additional component life cycle on each action called. React has its own optimization of doing multiple state updates at once and this is functional setState, I would give it another go, WDYT?

**Comment by didierfranc** [comment]
Yes don't hesitate to open a PR ;)

**Comment by elisherer** [comment]
Take a look #63

**Comment by didierfranc** [comment]
@nlucero @elisherer What do you think of that https://github.com/didierfranc/react-waterfall/pull/65 🤔

**Comment by didierfranc** [comment]
We can close this since v4 implement a solution, don't hesitate to reopen it ;)
