### ISSUE TITLE
Default mapper for /src/helpers/connect.js

### ISSUE THREAD

**Issue by fkerekiglobant** [didierfranc/react-waterfall#57]
A small suggestion: what about setting a default value `state=>state` for the mapStateToProps parameter? The definition of `connect` would then be:

```
const id = x => x;
const connect: CreateConnect = Consumer => (mapStateToProps = id) => WrappedComponent => {
```

and would let you write `Count = connect()(Count)` if you didn't care to select what properties of the store should be provided to a component? Am I missing anything, or should this work?

**Comment by didierfranc** [comment]
I think it's a good practice to enforce passing a selector function to connect if you want to override it the @elisherer tricks is the way to go.
