### ISSUE TITLE
Usage of Consumer?

### ISSUE THREAD

**Issue by fkerekiglobant** [didierfranc/react-waterfall#59]
The new Context works with Provider & Consumer, but though there is a Provider in the store created by createStore(), there is no Consumer anywhere... is that so? Shouldn't there be a Consumer to match the React specs? 

If there shouldn't be a Consumer, maybe the Provider word should be changed, so users wouldn't expect the React Context way of working?

**Comment by didierfranc** [comment]
This library is built on top of the context API it is not context API, v3 includes Consumer component it's been removed in the v4.
