### ISSUE TITLE
Allow provider to receive "initialState" as prop

### ISSUE THREAD

**Issue by slorber** [didierfranc/react-waterfall#60]
It's quite convenient to create the store at app startup time, but sometimes the initialState is not known at store creation time, but only when we mount the provider. In such case I'd like to create the store with no initialState = null, and only when provider is mounted, provide it with an initialState.

There are workarounds possible, like creating the store inside a React component, but it seems less convenient.

**Comment by didierfranc** [comment]
What about that ?

***store.js***
```js
const config = {
  actionsCreators: {
    hydrate: (_, state) => state
  }
}
```


***App.js***
```jsx
class App extends Component {
  componentDidMount() {
     const state = ...
     actions.hydrate(state)
  }

  render() {
    ...
  }
}
```

**Comment by slorber** [comment]
If componentDidMount is fired, then my provider is already mounted, so there's first a render with null state and then state is initialized (+ the setState call is not synchronous which can lead to unwanted behaviors in some cases imho). I don't think it's possible to hydrate before the mounting of the provider right? This would mean the state is not anymore in the React component and we are back to Redux

Currently I have a homemade draft implementation of what I'm looking for as an API for my app and see if react-waterfall could be used as a replacement as both solutions are very close. It looks like that:


```js

import React from 'react';

import { identity } from "lodash"
import { getGlobalState } from "api";
import { pure } from "recompose";

const {Provider, Consumer} = React.createContext(null);

export class GlobalStateProvider extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      globalState: this.props.initialState,
      globalStateAPI: {
        // TODO add other api methods here
        refresh: async () => {
          const newGlobalState = await getGlobalState();
          await this.updateGlobalState(_ => newGlobalState);
        },
      }
    };
  }

  updateGlobalState = (updateFn) => new Promise((resolve,reject) => {
    try {
      this.setState(state => {
        const newGlobalState = updateFn(state.globalState);
        return {globalState: newGlobalState};
      },resolve);
    } catch(e) {
      console.error("updateGlobalState error",e);
      reject(e);
    }
  });

  render() {
    return (
      <Provider value={this.state}>
        {this.props.children}
      </Provider>
    )
  }
}

export const GlobalStateConsumer = ({children}) => (
  <Consumer>
    {children}
  </Consumer>
);


export const connectGlobalState = (mapStateToProps = identity) => WrappedComponent => {

  // Make the connected component pure by default, as we don't want to re-render if globalState props do not change
  const PureWrappedComponent = pure(WrappedComponent);

  const ConnectedComponent = props => (
    <GlobalStateConsumer>
      {({globalState,globalStateAPI}) => (
        <PureWrappedComponent {...props} {...mapStateToProps(globalState)} globalStateAPI={globalStateAPI}/>
      )}
    </GlobalStateConsumer>
  );

  ConnectedComponent.displayName = `connectGlobalState(${WrappedComponent.displayName || WrappedComponent.name || 'Unknown'})`;

  return ConnectedComponent;
};

```

**Comment by didierfranc** [comment]
Future version with suspense will support this case, you'll be able to suspend render until hydratation for example. https://github.com/didierfranc/drum-roll

**Comment by slorber** [comment]
Yes, this would probably work but is less convenient than passing an initialState to the provider imho

**Comment by didierfranc** [comment]
I agree ;)

**Comment by didierfranc** [comment]
I added the ability to do that in the latest beta, with the most naive code, it could be great if you could test it ;)

https://github.com/didierfranc/react-waterfall/commit/1ba528d45331068cce9210d438a74c434183d6ae#diff-fd660e9b6b90f1c30d9c3336546a1c24R18

**Comment by slorber** [comment]
Thanks

Unfortunately I won't have time to test again this lib for the next 2 weeks :( but it looks nice so I guess it will work for me when I get back to it
