### ISSUE TITLE
createStore default() is not a function

### ISSUE THREAD

**Issue by mbbender** [didierfranc/react-waterfall#62]
I'm receiving an error when trying to use createStore()
```
TypeError: __WEBPACK_IMPORTED_MODULE_1_react_waterfall___default(...) is not a function
```

Code:
```
import createStore from 'react-waterfall'
import * as Api from './Api'

const initialState = {
  user: null,
}

const actionsCreators = {
  getUser: async () => {
    const user = await Api.getUser()
    return user
  },
}

const config = {
  initialState,
  actionsCreators,
}

const store = createStore(config)


export const {
  Provider,
  connect,
  actions,
} = store

```

**Comment by ieschalier** [comment]
I think you use v3 with v4 doc.

Documentation of v3 can be found [here](https://github.com/didierfranc/react-waterfall/tree/v3). But next version will be released [soon](https://github.com/didierfranc/react-waterfall/issues/54#issuecomment-392526318), so you can use @next version ;-).
