### ISSUE TITLE
Production sites using react-waterfall

### ISSUE THREAD

**Issue by RustyDev** [didierfranc/react-waterfall#66]
Just launched this site and am using Waterfall (v4.0.0-beta.2). I love how much less boilerplate there is coming from Redux and how easy actions are to use. The async actions in v4 were the main reason for switching. Never looking back!

https://addic.tech

**Comment by didierfranc** [comment]
I'm interesting to read more and more about your experience, which version are you using ?

**Comment by ieschalier** [comment]
I made this site in a couple of hours with react-waterfall 🎉.

I'm on v4.0.0-beta.3 of react-waterfall.

**Comment by nehaleem** [comment]
I'm also glad for this module! Just replaced whole redux with this module on my app and its waaaay simpler now.

**Comment by michal-autin** [comment]
@RustyDev 
> Just launched this site and am using Waterfall (v4.0.0-beta.2). I love how much less boilerplate there is coming from Redux and how easy actions are to use. The async actions in v4 were the main reason for switching. Never looking back!
> 
> https://addic.tech

I have some troubles running v4. Any chance there is a accessible repo with your code?

**Comment by RustyDev** [comment]
Sorry, I can't share the repo. Have you looked at the examples? This is the one I learned from:
https://github.com/didierfranc/react-waterfall/tree/master/examples/fetch
