### ISSUE TITLE
Opinions about the library after testing it in a project

### ISSUE THREAD

**Issue by gravitycode** [didierfranc/react-waterfall#68]
After having done a test of react-waterfall on a small project I would like to share some opinions with you. I have detected a number of problems/inconveniences that with other libraries like redux is solved.

- Regarding maintainability I do not see a good way to divide the functions of the actionCreators according to functional blocks without there being the probability of collision between the function names. My idea would be to be able to have namespaces by functional blocks.

```
actionCreators: {
    orders: {...},
    profile: {...}
    ...
}
```
In this way I could organize the actions in independent files without worrying about the collision of names between functions of different action.

- An action can alter the store on more than one occasion. It is common that when we have asynchronous calls we want to be able to notify the state view (LOADING, SUCCESS, ERROR). I do not see an easy way to do this with the current implementation. [see other comments](https://github.com/didierfranc/react-waterfall/issues/5)

These shortcomings, in my opinion, are insurmountable at the moment and it makes me think about changing the implementation to redux for the moment.

Thank you

**Comment by ktunkiewicz** [comment]
@gravitycode regarding second point, I also pointed this out recently and got into some discussion about this (check [here](https://github.com/didierfranc/react-waterfall/issues/55)).
I suggested changing action creator entry to something like this: `foo: (...args) => (state, actions) => { // foo code }`.

@didierfranc did [this](https://github.com/didierfranc/react-waterfall/commit/9ad7163884c4dc1d7e922d190a4c7de0d890978e#diff-1fdf421c05c1140f6d71444ea2b27638R64) change in result of these discussions.

Check latest beta version description: https://github.com/didierfranc/react-waterfall/releases/tag/v4.0.0-beta.3

**Comment by gravitycode** [comment]
Ah, I see that you have already turned this problem around. This recursive form I think is not valid for all scenarios or is very complex to implement when you manage two or more states. I do not see any advantage vs implementations like redux-thunk or redux-saga. At this point, some more power is expected. Thank you for your soon reply.

**Comment by elisherer** [comment]
I also like @ktunkiewicz 's suggestion, make it the same as [hyperapp](https://github.com/hyperapp/hyperapp) (A proven, good way of state management)
