### ISSUE TITLE
[HELP] actions are set in state instead of the passed value

### ISSUE THREAD

**Issue by desirelabs** [didierfranc/react-waterfall#69]
Hello, maybe I'm not implementing it the right way, but when I'm trying to set a value to my state with an action, the action is set in it instead.

Here an example : Click on the button should set the value "42" in the count, but console log in the action returns the actions, not the desired value.

[![Edit React Waterfall Store](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ypxw6mqv1v)

Another example implementing the todolist example:
[![Edit React Waterfall Store](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/18mq97vk77)

**Comment by nlucero** [comment]
Hi @desirelabs, since `4.0.0-beta.4` actions receive 3 parameters instead of 2: the current store state, the actions, and the action parameters. So your `set` action should be defined this way:

```
set: ({ count }, actions, value) => {
    return { count: count + value };
  }
```

https://codesandbox.io/s/o7k5rz42q6

**Comment by desirelabs** [comment]
Thanks @nlucero
