### ISSUE TITLE
Does this library work for serverside rendering?

### ISSUE THREAD

**Issue by jtremback** [didierfranc/react-waterfall#7]
It's been a while since I touched an "isomorphic" react app, and i'm not working on one now, but is it possible to use this library for that? Seems like the store is a global singleton. https://discuss.reactjs.org/t/facebook-flux-singleton-store-and-server-side-rendering/5652

**Comment by benbender** [comment]
SSR shouldn't be a problem. This library isn't based on a global singleton, but the new Context-API of React 16.3. See here: https://reactjs.org/blog/2018/03/29/react-v-16-3.html
