### ISSUE TITLE
Question: why is this clone of Redux better than Redux?

### ISSUE THREAD

**Issue by fedecarg** [didierfranc/react-waterfall#78]
What are the benefits of using this code/approach? Thanks

**Comment by tkvw** [comment]
Redux is framework agnostic, and react-waterfall requires React. Redux requires reducers to reduce the next state, so more setup is involved. `Redux-zero` does the same as `react-waterfall` and is framework independent, but the react implementation uses the unstable context (pre 16.3).

So the benefits are: easier to understand, simpler to use. Best is to start with redux and understand why you want to use this library.
