### ISSUE TITLE
reset/clear state for SSR?

### ISSUE THREAD

**Issue by tamagokun** [didierfranc/react-waterfall#80]
Trying to wrap my head around how to set this up for SSR, and I like the idea of having a single `store.js` that I can import from anywhere to get action creators or a Consumer.

However, when doing SSR, we want the state to be "fresh" for each request on the server. In particular when doing things outside of the context of a React tree. (i.e. next.js `getInitialProps`)

I'm not sure if a clear/reset mechanism is the answer here, or if there is a more elegant way achieve this. Thought i'd mention it here while I thought about it.

**Comment by tkvw** [comment]
How about setting it up in `_app.js`? You can always provide a different initial state to the provider from `getInitialProps`.

**Comment by tamagokun** [comment]
Right, that's the goal. At least, to do this once the next version of next.js lands. There is an issue with 6.1.1 where the new context API doesn't work on SSR in _app.js.

Anyways, the issue for me is that there isn't clear way to manage the store outside of a component-based API surface. With redux you get stuff like `getState()` and `dispatch` right from the store.

```js
import App, {Container} from 'next/app'
import React from 'react'
import { Provider } from '../store'

export default class MyApp extends App {
  static async getInitialProps ({ Component, router, ctx }) {
    let pageProps = {}

    // normally with something like redux, I can get dispatch and state from my store.
    // with react-waterfall, I only have connect, or a Provider. how can I get state here?
    // Also, if I call any actions at this point (before first render), the actions will throw because the Provider has not been set up yet, right?
    let state = {}
    ctx.state = state

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx)
    }

    return {pageProps, initialState: state}
  }

  render () {
    const {Component, pageProps, initialState} = this.props
    return <Container>
      <Provider initialState={initialState}>
        <Component {...pageProps} />
      </Provider>
    </Container>
  }
}
```

**Comment by tkvw** [comment]
> the issue for me is that there isn't clear way to manage the store outside of a component-based API surface

Maybe you want to look into middleware. What's your use-case?

**Comment by tamagokun** [comment]
Oh yeah, definitely seems like creating a middleware for this would work nicely. Main use case is for the downstream `Page` components to be able to have access to `state` and `actions` in their `getInitialProps` methods.

**Comment by mehrad77** [comment]
@tamagokun so why you closed this issue? is this problem solved?
