### ISSUE TITLE
Action not receiving value

### ISSUE THREAD

**Issue by mastikhor** [didierfranc/react-waterfall#85]
Trying to pass form value to the function via actions but actions not receiving the value.

**Login.js**
`
import {actions, connect } from '../../store';

class Login extends PureComponent {

  handleSubmit = (e) => {
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        console.log(values.email)
        actions.testAction(values.email)
      }
    }); 
    
  }
 }

const WrappedLoginForm = Form.create()(Login);
export default connect(({ user }) => ({ user }))(WrappedLoginForm)
`

**store.js**
`
import createStore from 'react-waterfall';

const config = {
    initialState: { 
      userLoggedIn: false,
      user:{
        email: "abc@xyz.com"
      }
     },
    actionsCreators: {
      testAction: ({user}, newValue) => ({
        user: { email: newValue }
      }),
    },
  }
  
export const {Provider, connect, actions} = createStore(config);
`

**Comment by SaphuA** [comment]
Welcome to github. Next time try to provide a little more info when asking a question, like the version you're using. Also formatting code is done with 3 ` characters, like so:
\`\`\`
code
\`\`\`

As for your question. If you're using v4 then your action should be:

    testAction: ({user}, actions, newValue) => ({
        user: { email: newValue }
    }),

The examples and documentation are currently broken.

**Comment by mastikhor** [comment]
Thanks! it worked.
