### ISSUE TITLE
Plans and roadmap?

### ISSUE THREAD

**Issue by SaphuA** [didierfranc/react-waterfall#89]
There are some pretty great suggestions and pull requests pending. Are there any plans on reviewing them? It would be a shame if these awesome contributors would head elsewhere. Also what are the plans for v4 and vNext? If you don't have the time to maintain this repo perhaps it would be a good idea to involve more people?

**Comment by didierfranc** [comment]
Time is expensive, I'm open if anyone want to help me to manage this library, I'm looking to the ≠ proposals, issues ...

**Comment by didierfranc** [comment]
https://github.com/didierfranc/react-waterfall/issues/91
