### ISSUE TITLE
The future of react-waterfall

### ISSUE THREAD

**Issue by didierfranc** [didierfranc/react-waterfall#91]
We're using `react-waterfall` in my entourage since February without any big issue, the simplicity of the implementation and the priceless fixes from the community has made it deadly stable.

I watched every issues, comments, pull request here and I think we can explore a lot of path for the next version so let's do it !

What if we'll make it even simpler ? recent React proposals like **Suspense** and **Hooks** make me think that creating a library to manage every aspect of a centralized state is useless. What if next version of react-waterfall or the next big thing in the world of ***React store management*** was just a set of tiny method to use the power of React with more convenience ?

#### 👉 This is what I'm doing with React 16.7
```js
import React, { createContext, useContext, useState } from "react";
import { storify }  from "react-waterfall";

const Context = createContext();
const { Provider } = Context;

const store = storify({
  state: [
    { text: "Code another javascript library", completed: false },
    { text: "Make this javascript library obsolete", completed: false }
  ],
  addTodo: (todos, todo) => [...todos, { text: todo }]
});

const TodoList = () => {
  let input;
  const state = useContext(Context);
  const addTodo = () => store.addTodo(input.value);

  return (
    <>
      <input ref={el => (input = el)} />
      <button onClick={addTodo}>+</button>
      {state.map(todo => (
        <div>{todo.text}</div>
      ))}
    </>
  );
};

const App = () => {
  const [state, setState] = useState(store.state);
  store.setGlobalSetState(setState);

  return (
    <Provider value={state}>
      <TodoList />
    </Provider>
  );
};

export default App;
```

**Comment by RustyDev** [comment]
+1. I love the simplicity. I agree that with suspense and hooks, that's the direction the library is going.

**Comment by marswong** [comment]
IMO, we need an example of how to design the store with multiple files in a large project, one-file store isn't ideal indeed :)

**Comment by RustyDev** [comment]
Have you checked out the [examples](https://github.com/didierfranc/react-waterfall/tree/master/examples)? The documentation for this library is a little sparse, but between the two examples, you can get a better sense of the possibilities.

**Comment by marswong** [comment]
absolutely i had checked out the examples and it's not a good practice to seperate state and actions.

**Comment by DimitryDushkin** [comment]
What about async actions in redux-thunk style? Without thunk-like functionality it is much more like https://reactjs.org/docs/hooks-reference.html#usereducer
