### ISSUE TITLE
Redux Dev Tools upgrade needed

### ISSUE THREAD

**Issue by digitive** [didierfranc/react-waterfall#93]
Redux Dev Tools update needed
Got warning in console:
`window.devToolsExtension` is deprecated in favor of `window.__REDUX_DEVTOOLS_EXTENSION__`

Can we update the redux dev tool plugin and replace the `window.devToolsExtension` with  `window.__REDUX_DEVTOOLS_EXTENSION__`.

Thanks.

**Comment by didierfranc** [comment]
Just published v4.0.1 tell me if it's better ;)

**Comment by digitive** [comment]
Awesome! thank you so much for your excellent job!
