### ISSUE TITLE
Change state multiple times in an action

### ISSUE THREAD

**Issue by digitive** [didierfranc/react-waterfall#94]
Is there any way ( or example ) to change the store state multiple times within an async action? 
For example: in an initializeAction it may send multipile requests to backend step by step (and may also based on some if-else logic). Front-end should be updated accordingly mutiple times. In redux, this can be done by call dispatch() multiple times.  
Thanks.

**Comment by didierfranc** [comment]
Maybe what you're looking for is that kind of pattern https://github.com/didierfranc/react-waterfall/blob/master/examples/fetch/src/store/index.js#L13-L22

**Comment by digitive** [comment]
Well, not exactly. Actually, I am try to find a way to set state multiple times inside an action, and each setState should trigger the ui updates. Though this could be done via calling other actions, still wondering more straight forward way to trigger state change instead of return only one state.

**Comment by didierfranc** [comment]
You can't do that with redux, same here `(action, state) => state` but you can chain it

**Comment by digitive** [comment]
Something like this:

export function getEventList(filterText) {
  return async (dispatch, getState) => {
    try {
      const state = getState();
      const accountId = getActiveAccountId(state);
      ...
      dispatch({ type: GET_EVENT_LIST_LOADING, payload: { accountId } });

      const {
        eventList,
        events,
        timestamp,
      } = await api.getEventList(filterText);

      if (events) {
        extendEvents(events.list, state);
      }
      dispatch({ type: GET_EVENTS_COMPLETE, payload: eventsPayload });
      dispatch({ type: GET_EVENT_LIST_COMPLETE, payload: eventListPayload });
    } catch (err) {
      dispatch({ type: GET_EVENT_LIST_ERROR, payload: err });
    }
  };
}
