### ISSUE TITLE
Router: Store returns to initialState on loading different page

### ISSUE THREAD

**Issue by vincentrohde** [didierfranc/react-waterfall#97]
I am using the `react-router-dom` v4 module for my project.

If I add items to my store, they appear in the view. However, if I switch to a different page/ route and return to my page, the items are gone. The state is back at the initialState.

This is my structure:

```
Router > Switch > Route
  Lane(using the Provider)
    Rooms(using connect, actions)
```
What am I missing here? Why is it not saving the updates in the store?

**Comment by blakeperdue** [comment]
You may need to bump your Provider up in the tree to be above the Router.

**Comment by vincentrohde** [comment]
Thanks for the reply, that's exactly what helped to fix the issue. I wrapped the Provider around the Router:

```
<Provider>
    <AppRouter />
</Provider>
```
The full source code(how i implemented the fix) can be found in the close for this issue:
vincentrohde/iot_app#55
